### ISSUE TITLE
Stimuli Format in Simon and Shape/Color Shifting Tasks

### ISSUE THREAD

**Issue by aproje** [tatool/tatool-web#100]
We noticed differences in format for the Simon and Shape/Color Shifting tasks. Everything looks perfect on widescreen monitors, but not on laptops. I attached photos for each. Is there a way to ensure that the stimuli stay centered whether our participants use a desktop, laptop, or widescreen monitors?
![simon](https://user-images.githubusercontent.com/33902157/35146290-d9ee63c4-fd0a-11e7-9b37-f3432f868f2f.PNG)
![shape_color_shifting](https://user-images.githubusercontent.com/33902157/35146299-e1165a4e-fd0a-11e7-883d-a0f3539ea330.jpg)

**Comment by alocher** [comment]
That's odd. I've just tested the Simon task on Chrome/Firefox/IE and wasn't able to reproduce the issue. Can you let me know what OS and browser (incl version) your using for this test? What is the screen resolution of this laptop?

**Comment by aproje** [comment]
The top picture (Simon) is from this laptop:
OS: Microsoft Windows 10 Pro 
Browser: Microsoft Edge 41.16299.15.0
Screen resolution: 2256 x 1504

The bottom picture (Shape/Color Shifting) is another laptop:
OS: Microsoft Windows 10 Home
Browser: Mozilla Firefox Version 57.0.4 (64-bit)
Screen resolution: 1366 x 768

**Comment by alocher** [comment]
Thanks for the detail. Unfortunately I couldnt find anything in my tests yet. Is there any chance you could test a few things on one of these laptops?

Let's focus on the Simon task for now.
- Can you run the public module "Simon Experiment" to make sure it's not caused by a custom module?
- Can you run this module on different browsers on one of these machines and see if they all behave the same?

**Comment by Ascronia** [comment]
I tested the following on my one laptop where I could replicate the problem:

Simon Experiment Public Module:
- Microsoft Edge - _issue does not occur but strange scrollbar behavior_
- Google Chrome - issue does not occur
- Mozilla Firefox - issue does not occur

Our Custom Module (Trial runs):
- Microsoft Edge - _issue does not occur but strange scrollbar behavior_
- Google Chrome - issue does not occur
- Mozilla Firefox - issue does not occur

Our Custom Module (Test runs):
- Microsoft Edge - **_issue does occur_**
- Google Chrome - issue does not occur
- Mozilla Firefox - issue does not occur

Interestingly, in Chrome and Firefox, no scrollbar is shown at the bottom of the screen at all (as it should be, I suppose).
In Microsoft Edge (where the issue occurs) always a scrollbar is shown at the bottom (for the public and custom modules). Each time when I click on the right or left arrow, the scrollbar shifts accordingly (simultaneously to the stimulus being refreshed). However, in the public module and the trial runs of our custom module, this shift is followed by an immediate re-centering of the screen (which keeps the desired visual configuration stable). However, this does not happen for our test runs (where the visual configuration is being affected without "re-centering").

We will now check whether there are any setting differences between our trial and test runs that could be responsible for the difference in re-centering.

However, Microsoft Edge definitely seems to be behaving differently than the other two browsers (scrollbar vs. none) and when the scrollbar is shown, the arrow presses affect the scrollbar and shift the image accordingly.

**Comment by alocher** [comment]
That's some great testing there. Thanks for the hint with the scrollbar and the arrows. I can see that this could potentially be an issue if the arrows scroll the window which would lead to stuff not being centered anymore. I'll have a look what we can do here.

**Comment by alocher** [comment]
The issue with the IE scroll bar should now be fixed. Let me know if this works for you as well.

**Comment by aproje** [comment]
I just tested our custom module and saw that the stimuli in the Shape/Color Shifting and Parity/Magnitude Tasks are now centered. Thanks so much!
