### ISSUE TITLE
English Tower of Fame Instructions

### ISSUE THREAD

**Issue by aproje** [tatool/tatool-web#102]
I suggest some revisions to the English Tower of Fame instructions:
en_tower_03.htm - change "beside" to "adjoining" to be consistent with the stimuli text
en_tower_04.htm - put space between "above" and "each"

Please let me know if this is the right place to make such requests. I'll be making similar ones for the German tasks, just a lot more.

**Comment by alocher** [comment]
This is the perfect place for this. I've just done these changes.
