### ISSUE TITLE
Stimuli Buttons for German Tasks

### ISSUE THREAD

**Issue by aproje** [tatool/tatool-web#103]
I created a battery for German tasks using Editor and noticed that the stimuli buttons are in English. Is it possible to translate the stimuli buttons for these tasks:

1. Simon Task - "rot" instead of "red", "grün" instead of "green"
2. Flanker Task - "Vokal" instead of "vowel", "Konsonant" instead of "consonant"
3. Shape/Color Shifting - "rund" instead of "round", "eckig" instead of "angular", "blau" instead of "blue", "grün" instead of "green"
4. Parity/Magnitude - "ungerade" instead of "odd", "gerade" instead of "even", "kleiner" instead of "less", "grösser" instead of "greater"
5. Brown-Peterson - "ungerade" instead of "odd", "gerade" instead of "even"

**Comment by alocher** [comment]
These values are all managed through the stimuli files. You can download the corresponding stimuli file and do the changes yourself and upload it to your own hosting or provide them for re-upload if you like.

You should be able to find all stimuli files either via the task library:
http://www.tatool-web.com/#/doc/lib-exp-simon.html

Or by browsing to the correct project stimuli folder on github:
https://github.com/tatool/tatool-web/tree/master/app/projects/public

For example the Simon Task color stimuli file can be found here: https://github.com/tatool/tatool-web/blob/master/app/projects/public/tatool-stimuli/stimuli/simon-colors.csv

Hope that helps.

**Comment by aproje** [comment]
If I provide the stimuli files, would you be able to re-upload them? For example, the Simon Task we used is from the project stimuli folder in the uzh-ef-battery:
https://github.com/tatool/tatool-web/tree/master/app/projects/public/uzh-ef-battery/stimuli

I attached the files in case this is possible. I can work on the other German tasks if it works.

![simon_green_left_de](https://user-images.githubusercontent.com/33902157/35981485-a645ec84-0ced-11e8-8c4a-8f361163eef0.png)
![simon_red_right_de](https://user-images.githubusercontent.com/33902157/35981486-a6945b08-0ced-11e8-9589-7cf2faa774a8.png)

[ef_inhibition_simon_practice_de.txt](https://github.com/tatool/tatool-web/files/1707666/ef_inhibition_simon_practice_de.txt)
[ef_inhibition_simon_de.txt](https://github.com/tatool/tatool-web/files/1707667/ef_inhibition_simon_de.txt)

**Comment by alocher** [comment]
Awesome, I've uploaded them and you should be able to use them in your editor now within the same project.

**Comment by aproje** [comment]
Here are the stimuli files for Shape/Color Shifting found in https://github.com/tatool/tatool-web/tree/master/app/projects/public/uzh-ef-battery/stimuli. I hope they're all good. Please let me know. Others to follow.

![shifting_round_de](https://user-images.githubusercontent.com/33902157/36104157-839d8d78-1011-11e8-824e-79cd82dad56d.png)
![shifting_angular_de](https://user-images.githubusercontent.com/33902157/36104170-893fe37a-1011-11e8-99fa-d0800f182f44.png)
![shifting_blue_de](https://user-images.githubusercontent.com/33902157/36104179-8f04d31a-1011-11e8-8993-1f65b70db612.png)
![shifting_green_de](https://user-images.githubusercontent.com/33902157/36104186-96370dc4-1011-11e8-8305-b0158f43aceb.png)
[ef_shifting_figural_single_color_1_de.txt](https://github.com/tatool/tatool-web/files/1716809/ef_shifting_figural_single_color_1_de.txt)
[ef_shifting_figural_single_color_2_de.txt](https://github.com/tatool/tatool-web/files/1716810/ef_shifting_figural_single_color_2_de.txt)
[ef_shifting_figural_single_color_practice_de.txt](https://github.com/tatool/tatool-web/files/1716811/ef_shifting_figural_single_color_practice_de.txt)
[ef_shifting_figural_single_shape_1_de.txt](https://github.com/tatool/tatool-web/files/1716812/ef_shifting_figural_single_shape_1_de.txt)
[ef_shifting_figural_single_shape_2_de.txt](https://github.com/tatool/tatool-web/files/1716813/ef_shifting_figural_single_shape_2_de.txt)
[ef_shifting_figural_single_shape_practice_de.txt](https://github.com/tatool/tatool-web/files/1716814/ef_shifting_figural_single_shape_practice_de.txt)
[ef_shifting_figural_mixed_practice_de.txt](https://github.com/tatool/tatool-web/files/1716815/ef_shifting_figural_mixed_practice_de.txt)
[ef_shifting_figural_mixed_de.txt](https://github.com/tatool/tatool-web/files/1716816/ef_shifting_figural_mixed_de.txt)

**Comment by aproje** [comment]
Here are the stimuli files for the Brown-Peterson found in https://github.com/tatool/tatool-web/tree/master/app/projects/public/tatool-stimuli/stimuli

![parity-even-right_de](https://user-images.githubusercontent.com/33902157/36105535-27185944-1015-11e8-898a-245f2e8c008d.png)
![parity-odd-left_de](https://user-images.githubusercontent.com/33902157/36105546-2d2e62ce-1015-11e8-8f11-6d1bca431c9a.png)
[choice-parity_de.txt](https://github.com/tatool/tatool-web/files/1716900/choice-parity_de.txt)

**Comment by alocher** [comment]
All stimuli have been uploaded and should be available. I noticed the font and color of the arrows on the parity looks a bit off if you want to fix that.

**Comment by aproje** [comment]
Ok, we fixed it. Here are the revised files for the Brown-Peterson found in https://github.com/tatool/tatool-web/tree/master/app/projects/public/tatool-stimuli/stimuli

![parity-even-right_de](https://user-images.githubusercontent.com/33902157/36198445-f5ca96d2-1176-11e8-8e1a-e79f1b00539a.png)
![parity-odd-left_de](https://user-images.githubusercontent.com/33902157/36198446-f5e2e67e-1176-11e8-80a6-9fde67f4ab5f.png)

We also improved the image files for the inhibition tasks so that the stimuli button color remains the same. Please re-upload these in https://github.com/tatool/tatool-web/tree/master/app/projects/public/uzh-ef-battery/stimuli

![shifting_angular_de](https://user-images.githubusercontent.com/33902157/36198547-2db5a85c-1177-11e8-9459-b15f9edc0b01.png)
![shifting_blue_de](https://user-images.githubusercontent.com/33902157/36198548-2dce63ce-1177-11e8-94d2-902d4337329f.png)
![shifting_green_de](https://user-images.githubusercontent.com/33902157/36198549-2de5dfea-1177-11e8-80e1-8e8994561c3b.png)
![shifting_round_de](https://user-images.githubusercontent.com/33902157/36198550-2dfe2622-1177-11e8-8c21-77192ca82758.png)
![simon_green_left_de](https://user-images.githubusercontent.com/33902157/36198552-2e1928be-1177-11e8-8462-b73ad1394ad3.png)
![simon_red_right_de](https://user-images.githubusercontent.com/33902157/36198554-2e462512-1177-11e8-984d-d87e90dfd45d.png)

Thanks!

**Comment by alocher** [comment]
The new images have been uploaded.

**Comment by aproje** [comment]
Excellent, thanks!

Could you please check if these stimuli files for the Flanker Task found in https://github.com/tatool/tatool-web/tree/master/app/projects/public/uzh-ef-battery/stimuli work? We wanted to translate the words "vowel" and "consonant".

[ef_inhibition_flanker_de.txt](https://github.com/tatool/tatool-web/files/1727298/ef_inhibition_flanker_de.txt)
[ef_inhibition_flanker_practice_de.txt](https://github.com/tatool/tatool-web/files/1727299/ef_inhibition_flanker_practice_de.txt)

**Comment by alocher** [comment]
These stimuli files have been uploaded (renamed to *.csv)

**Comment by aproje** [comment]
Thanks so much, it's working now!
