### ISSUE TITLE
English Stroop Instructions

### ISSUE THREAD

**Issue by aproje** [tatool/tatool-web#106]
I'd like to suggest some revisions to inhibit_stroop_02.htm:
1. change "...you'd have to press the key 4..." to "...you'd have to press key 4..."
2. change "...you'd have to press the key 3." to "...you'd have to press key 3."
3. change "...you'd have to press the key 4." to "...you'd have to press key 4."

**Comment by alocher** [comment]
Pending update to uzh-ef-battery/instructions/inhibition_stroop_example.png

**Comment by cvonbastian** [comment]
Thanks for letting us know. All updated and uploaded.
