### ISSUE TITLE
English Brown-Peterson and Letter Task Instructions

### ISSUE THREAD

**Issue by aproje** [tatool/tatool-web#107]
May I suggest revisions to these English instructions:
1. Letter - updating_letter_03.htm
   change "...consonants at their respective position." to "...consonants at their respective position**s**."

2. Brown-Peterson - tatoolBrownPeterson.html
   change "Press Left Arrow if the digit is odd." to "Press the left arrow key if the digit is odd."
   change "Press Right Arrow if the digit is even." to "Press the right arrow key if the digit is even."

**Comment by alocher** [comment]
Pending update to uzh-ef-battery/instructions/letterposition_example.png

**Comment by cvonbastian** [comment]
Thanks for pointing this out and sorry for the long wait; I've updated the image.
