### ISSUE TITLE
No Stimuli Buttons for German Parity/Magnitude Task 

### ISSUE THREAD

**Issue by aproje** [tatool/tatool-web#108]
Does the German parity/magnitude task found in https://github.com/tatool/tatool-web/tree/master/app/projects/public/uzh-shifting-battery/modules really have no stimuli buttons? I seem to recall that it had them before.

**Comment by cvonbastian** [comment]
Hi there! You're right, they indeed do. They were accessible through Tatool Web, but I forgot to upload them to GitHub. They're available now: https://github.com/tatool/tatool-web/tree/master/app/projects/public/uzh-ef-battery/stimuli (look out for the prefix 'de').
