### ISSUE TITLE
Firefox problems with Editor

### ISSUE THREAD

**Issue by ppyyrryy** [tatool/tatool-web#111]
Dear Developers,

Since a few days, I experience problems while working with Tatool Web Editor in Firefox. When I try to test my modules or export data, Firefox's Web Console gives me:

```
uncaught exception: [object Event]  (unknown)
InvalidStateError  vendor.min.js:82:1369
```
This happens in a couple of different versions of Tatool Web, installed on separate machines, that have had no issues before. Firefox version ESR; 52.8.1 (64-bit).

This doesn't happen in Chromium  66.0.3359.117 (Developer Build).

Possibly related to somehow outdated ESR release but still a very inconvenient cross-browser issue.

I appreciate if you can look at this.

**Comment by alocher** [comment]
Thanks for reporting this, I'll have a look what I can find.

**Comment by ppyyrryy** [comment]
Hi, this problem disappeared just as quickly as it appeared. Now with Firefox ESR; 52.9.0 (64-bit).

**Comment by alocher** [comment]
I'm glad it did ;)
