### ISSUE TITLE
Allow for audio stimuli for dual n-back task

### ISSUE THREAD

**Issue by JackyHarvey** [tatool/tatool-web#112]
Hi everyone, 

We are trying to develop the dual n-back task for Tatool Web which needs both visual and audio stimuli. Would it be possible to modify the main executable to allow for this? 

Is there another way of adding audio stimuli? 

Regards, 
Jacky

**Comment by alocher** [comment]
Hi Jacky,
You're lucky or you had something to do with the Pull Request from @bitbrain-za that came in just a day after you requested this :)

https://github.com/tatool/tatool-web/pull/113

I'll look into testing this feature and merge it into the main release.

Cheers,
André

**Comment by alocher** [comment]
This feature has now been put live in v1.3.1.

https://github.com/tatool/tatool-web/releases/tag/v1.3.1
