### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by aher19** [tatool/tatool-web#121]
Hello,
I was trying to install tatoolweb on a laptop but it did not work and I received several error messages. I have to admit I am not very much skilled in programming, that is why I am posting the problem and I apologize for the inconveniences. 
Attached is the error message I received when installing tatool. I followed the instructions on the homepage and also installed the other two programs beforehand.

Many thanks and best wishes. AHer

![problemtatool2](https://user-images.githubusercontent.com/46324604/50600122-6ef39180-0eb0-11e9-8974-4e575c016226.PNG)

**Comment by alocher** [comment]
Hi there, before going any further can I just ask to make sure that you're planning to run your own installation of tatool web incl. programming your own tasks instead of just using existing tasks with your own stimuli on tatool-web.com? Just making sure you don't go through this process if it's not required for your requirements.

Did you run through all "[Getting Started](https://www.tatool-web.com/#/doc/dev-getting-started.html)" steps in the documentation? Did npm run setup return any error?

**Comment by aher19** [comment]
Hello, thank you for your fast reply. For a online test battery, we are looking for a processing speed task and thought of the choice reaction time task from the task library, but we also have some tasks of our own, where we were thinking of adapting them to tatool (but not right now). However, given that I am quite unexperienced with programming I was thinking of trying out already an existing task to familiarize myself with tatool-web. Again, I am sorry for the inconveniences and yes, I had some errors with npm as well.

**Comment by alocher** [comment]
Sounds good! So, in case you want to just use the choice-reaction time task with different stimuli and instruction, you actually don't have to install anything. Instead, you'd just use the online platform (www.tatool-web.com) with a researcher account. This won't require any programming at all. Alternatively, if you plan on learning programming (e.g. by adjusting an existing task like the choice-reaction time task), you will have to install tatool web locally (but you can still run your tasks through the online platform if you wish so, see "Can I run my custom Executables on tatool-web.com?" in our [FAQ](https://www.tatool-web.com/#/doc/main-faq.html)). If so, could you please try installing tatool web again and post the exact npm error message that you receive?
