### ISSUE TITLE
Saving problem

### ISSUE THREAD

**Issue by lvxiangyu11** [tatool/tatool-web#126]
您好，我在使用您提供的最新tatool-web时，在他人保存数据时，出现如下错误
Hello, when I am saving the survey data in tatool-web, i have encountered this problem.
Hallo, ich sprechen nitch gut Deutsch. Biite im Englisch oder im Chinesisch  austauschen. Vielen danke.

_______________________________the following Bugs infos_________________________
(node:384) DeprecationWarning: current URL string parser is deprecated, and will
 be removed in a future version. To use the new parser, pass option { useNewUrlP
arser: true } to MongoClient.connect.
You can now access tatool on iZf3l2623fhoj9Z:3000
(node:384) DeprecationWarning: collection.ensureIndex is deprecated. Use createI
ndexes instead.
Running tatool in LAB mode.
(node:384) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDel
ete()` without the `useFindAndModify` option set to false are deprecated. See: h
ttps://mongoosejs.com/docs/deprecations.html#-findandmodify-
C:\19-8-15\tatool-web-master\controllers\exportCtrl.js:60
            zip.bulk([{src: [uploadPath + '*' + req.user.code + '*.csv'], dest:
'', expand: true, flatten: true}]).finalize();
                ^

TypeError: zip.bulk is not a function
    at C:\19-8-15\tatool-web-master\controllers\exportCtrl.js:60:17
    at C:\19-8-15\tatool-web-master\node_modules\graceful-fs\graceful-fs.js:57:1
4
    at FSReqWrap.oncomplete (fs.js:141:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tatool-web@1.3.0 start: `node server.js lab prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tatool-web@1.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-08-15T0
3_34_31_217Z-debug.log

**Comment by alocher** [comment]
Hi there,

Unfortunately I wasn't able to reproduce the error. the error seems to indicate that the the method bulk() doesn't exist for one of the dependencies ("archiver": "0.21.0"). The method seems to be deprecated for later versions, but the version we currently depend on should work just fine.

Can you tell me what version of node.js you're using and maybe try another "npm run setup"?

**Comment by lvxiangyu11** [comment]
Oh, yes. It seemed that the Nodejs version is upper. When I use "npm install" command, it shows
_______________________________________________________________________
 that"audited 24417 packages in 20.211s
found 87 vulnerabilities (52 low, 15 moderate, 20 high)
  run `npm audit fix` to fix them, or `npm audit` for details"
_______________________________________________________________________
so I run the "npm audit fix" command to fix the problem, this make a trouble.
And clean the environment and run "npm run setup" instead, it really works. Thank you so much. :-)
