### ISSUE TITLE
Website contact not working!

### ISSUE THREAD

**Issue by andyleynes** [tatool/tatool-web#135]
Hi, I tried clicking on all the contact links in your tatool webpage. They all return errors (using chrome). I would like to get in touch about hosting stimuli and executables.  I also may have some questions along the way. Please advise. Thanks in advance.

**Comment by cvonbastian** [comment]
Hi Andy, thanks for making us aware of the broken links, I'll fix them asap. You can get in touch with us via email: info [at] tatool.ch . Looking forward to hearing from you!
