### ISSUE TITLE
developer access

### ISSUE THREAD

**Issue by sanjanahebbar** [tatool/tatool-web#141]
i am hereby requesting for the editor/developer access to my account on tatool

**Comment by cvonbastian** [comment]
Hi sanjanahebbar, please let me know your email address that you've signed up with (you can email it to info@tatool.ch if you prefer) and I'll update your user account. 
-Claudia

**Comment by cvonbastian** [comment]
Thanks for your email. I've upgraded your account so that you should now have developer/editor access the next time you log in.
