### ISSUE TITLE
Problems in creating complex span module

### ISSUE THREAD

**Issue by MehtapTufan** [tatool/tatool-web#146]
Hi,
I am a researcher at Atılım University in Turkey. I want to use your own complex span experiment module for collecting data but I could not create it in editor part. When I clicked open button and select your demoComplexSpan.json file, it gives an error as "Syntax Error in module file: Maximum call stack size exceeded". What should I do? How can I use your module for data collection?

Kind regards,
Mehtap Tufan

**Comment by alocher** [comment]
Hi Mehtap, I was able to reproduce the error and will look at coming up with a fix asap. Thanks for reporting.

**Comment by alocher** [comment]
Hi, this issue should now be fixed. Let me know if you still encounter any issues with this.
