### ISSUE TITLE
Website dns error

### ISSUE THREAD

**Issue by gianpieropapappicco** [tatool/tatool-web#147]
The website is not reachable. 
I tried from multiple devices and multiple connections
![Cattura](https://user-images.githubusercontent.com/28351941/108422331-b840ff80-7236-11eb-8e96-11bf6462bb85.PNG)

**Comment by alocher** [comment]
We had to switch our domain hosting and DNS refresh will take 24-48 hours unfortunately. This should hopefully resolve itself quickly.
