### ISSUE TITLE
Hello, I am new to tatool and I am trying to add some survey questions after completing the cognitive tasks (multiple choice questions, likert scale, select all that apply). Does anyone know how to add a component that resembles this?

### ISSUE THREAD

**Issue by jnash190** [tatool/tatool-web#149]
Hello, I am new to tatool and I am trying to add some survey questions after completing the cognitive tasks (multiple choice questions, likert scale, select all that apply). Does anyone know how to add a component that resembles this?

**Comment by cvonbastian** [comment]
Answered in [Discussions](https://github.com/tatool/tatool-web/discussions/148).
