### ISSUE TITLE
Download / Access

### ISSUE THREAD

**Issue by ElisaAdam** [tatool/tatool-web#153]
Hi, 

I just created an account with developer access. I can see the "Editor" and "Analytics" tags at the header, so I assume to actually have developer rights. However, I wonder how to download modules? I tried to follow the instructions given by the "Introduction" tutorial but if I try to download the Flanker Demo task, only a window with source code would open without any option for download of the module. Consequently, the module would not appear in the "Editor" view - there I could only upload data from my own computer. The problem occurs with any test from the library in that download is not possible.

I even created a new account with another email address - but the same problem occurs.

I hope to find some help here asap. 

Thanks in advance!
Regards, Elisa

**Comment by alocher** [comment]
You will have to download the Module json file (Save as...). This can be done by right clicking on the link. Afterwards you can open the module file in your Tatool Editor according to the instructions:

"How to import a module from JSON
The Open button at the top right of the Editor screen allows you to create a module from a *.json file, such as one that you previously exported. An imported Module will always create a new entry and never replace an existing module (even if they have the same name)."

**Comment by ElisaAdam** [comment]
Thank you - that did work! Unfortunately, I face some severe problems adapting the chosen module but that is another issue... Perhaps that is simply not possible.
