### ISSUE TITLE
Obtaining a link for modules added to My Modules

### ISSUE THREAD

**Issue by Esterng93** [tatool/tatool-web#155]
Hello, I have several modules on My Modules that I have added from publicly available modules. I also have a task I created under Editor. In the task I have under Editor, I can obtain a URL that I've been using to send to my participants to take the task. However, in the modules I've added under My Modules I can't edit anything or obtain a link. I haven't been able to obtain information about what one can do with the tasks on My Modules. Is there a way for me to use the tasks I've added under My Modules (e.g., to transfer them to Editor) so I don't need to create the tasks from scratch on Editor?

Thank you!

**Comment by cvonbastian** [comment]
Hi Esterng93 and apologies for the late reply - your post has totally fallen between the cracks and I've come across it only now. I assume meanwhile you'll have figured it out already, but as others might wonder about this as well, I'll still reply: 

The modules you add under My Modules are modules that have been created by other researchers for collecting data or, in the case of modules from Tatool, to provide demo modules so people can try out the tasks. You would need to get in touch with the authors of the module to ask them to share their JSON/module file, if they provide contact information in the description. 

That said, modules from Tatool can be downloaded from GitHub. When you browse our [Task Library](https://www.tatool-web.com/#!/doc/main-lib.html), you can find links to the demo module files under "Demo".
