### ISSUE TITLE
Editor start: 404 error in "developer" folder (should be the "projects" folder instead?)

### ISSUE THREAD

**Issue by birdcw** [tatool/tatool-web#36]
I'm new to tatool, so I'm starting with the executables tutorial (http://www.tatool-web.com/#/doc/dev-executable-templates.html). My js and html files are in the projects folder, as directed in the tutorial: 

app/projects/public/myExperiment/executables

However, terminal is showing that tatool is looking for those files in a "developer" folder when I start the experiment in the editor:

GET /developer/resources/public/tatool/executables/myExperiment.service.js?token=F02
00vIW1425413876282 404 4.943 ms - 33
GET /developer/resources/public/tatool/executables/myExperiment.css?token=F0200vIW14
25413876282 404 3.053 ms - 33
GET /developer/resources/public/tatool/executables/myExperiment.service.js?token=F02
00vIW1425413876282 404 3.912 ms - 33
GET /developer/resources/public/tatool/executables/myExperiment.ctrl.js?token=F0200v
IW1425413876282 404 4.360 ms - 33

**Comment by alocher** [comment]
Hi birdcw,

don't be fooled by the url request path as it will not exactly match your folder path. What I can see though is that tatool is looking in the tatool project/folder as you can see in the query string:

/developer/resources/public/**tatool**/executables/myExperiment.service.js?token=F02
00vIW1425413876282

So when you're creating your Module in the Editor make sure to select the correct project for your Executable. You can select the project by clicking on the blue edit button next to *Type* in your Executable (first input) and then select your *myExperiment* project (which you should have created already). In the second dropdown you should also be able to select your Executable as you've set it up during the project configuration step. I would expect this to be myExecutable and not myExperiment as in your 404 messages.

Let me know if it works out.

**Comment by birdcw** [comment]
@alocher got it, that was the solution. Thanks
