### ISSUE TITLE
Cannot see anything after starting the localhost , yields blank page.

### ISSUE THREAD

**Issue by Rajeevmotwani7** [tatool/tatool-web#90]
I am starting tatool-web for the first time. I have allowed everything on my google chrome browser but still I cannot see the webpage. Kindly help regarding the issue.

![image](https://user-images.githubusercontent.com/19506368/31334702-a855cc8c-acef-11e7-8661-94123eb89673.png)

**Comment by alocher** [comment]
Looks like some dependencies might not have installed correctly. If you open the Console in Chrome (by pressing F12) you should see a bunch of error messages. Can you go back to the console and run the following commands in the tatool-web folder:

1. bower install
- if no error then continue with
2. gulp build
- if no error then continue with
3. npm install
- if no error then try running Tatool Web again.

**Comment by Rajeevmotwani7** [comment]
I am getting following error in the last step i.e. npm install

![image](https://user-images.githubusercontent.com/19506368/31337979-e2777506-acfd-11e7-8e9c-72d3ad1d65f1.png)

**Comment by alocher** [comment]
Alright, let's try something radical.
Delete the folder node_modules in your tatool-web-master folder and try running this to reinstall everything again:
npm install npm@latest -g

**Comment by Rajeevmotwani7** [comment]
I tried that in the first time before I posted the screen print. Anyways, I found the solution. I just ran the same three commands with the error in the form npm install -> bower install -> gulp build and it worked. Although still not clear to me how it worked.

**Comment by alocher** [comment]
I'm glad it works. Looks like something went wrong during the install of all the dependencies, so basically by deleting node_modules first, you made sure that everything is downloaded again. Odd one indeed.

**Comment by Rajeevmotwani7** [comment]
Yes, Thank you so much for the help :)
