### ISSUE TITLE
Missing Instruction for Parity/Magnitude Shifting Task

### ISSUE THREAD

**Issue by aproje** [tatool/tatool-web#98]
Hello!

I added a practice trial for the parity/magnitude task in English, which made it necessary to add instructions. I added a PNG instruction from Cloudinary (images) after the first one in html (pages). Somehow the PNG doesn't show up and I go straight to the countdown after the html instruction. I've combined images and pages before and those worked, so I don't know why this isn't working. Could you please help?

Kith

**Comment by alocher** [comment]
Could you share the module file so I can get an idea of the configuration?
You can save the module as a json file if you open your module in the Editor Tab and press the Download button at the bottom of the popup editor dialog,

**Comment by aproje** [comment]
Hi Andre

Sorry for the late reply. I'm not here every day and have actually begun my holiday break. In case you reply after I log off, I'll get back to you mid-January.

It says that the JSON file type isn't supported. Hope Word is ok.
[EFWM.docx](https://github.com/tatool/tatool-web/files/1575800/EFWM.docx)

**Comment by aproje** [comment]
Happy New Year, Andre!

I tested the battery several times, and I realized that actually, only the html (pages) instructions come out. The png (images) instructions never show up, so I guess I can't combine both in one executable, is that right?

**Comment by alocher** [comment]
I see what you mean. You can definitely only use html or images within one Executable and not both (see Instruction [documentation](http://www.tatool-web.com/#/doc/lib-acc-instruction.html)). You could just add two Instruction Executables in sequence to achieve this though.

**Comment by aproje** [comment]
Yes, that‘s what I thought. Thanks, will try it right away.
