### ISSUE TITLE
Inserting Child at the Start or Middle of a Battery

### ISSUE THREAD

**Issue by aproje** [tatool/tatool-web#99]
I finished creating a battery for our study using Editor, but now I need to add a child (executable) at the very beginning. Is there a way to do this without undoing all the rest of the battery? And what if I want to add a child in the middle of the battery?

**Comment by alocher** [comment]
If you click on your root element you can then add a child element. By default this elements gets added as the last child of the parent. You can then move the element up and down with the Up/Down buttons next to the Add Child button.

**Comment by aproje** [comment]
Great! For a minute there I thought I had to rewrite everything, what a relief. Thanks a million!
